# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: ping_test_concept_using_file_or_list_input
# label used for menu selection
label: ping URLs or IPs to get response results
description: |
  ping a list of URLs or IPs to get min/max/avg response times.
  Input can be a user entered list or file
type: python

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Prisma Access

# ---------------------------------------------------------------------
# end of preamble section

# variables section

input_type, file_name, url_list

variables:
  - name: input_type
    description: select to use entered list or file input for the ping targets
    default: list
    type_hint: dropdown
    dd_list:
      - key: file
        value: file
      - key: list
        value: list

  - name: url_list
    description: list of URLs or IPs to ping
    default: []
    type_hint: list
    toggle_hint:
      source: input_type
      value: list

  - name: file_name
    description: file with target ping list
    default: some_file.txt
    type_hint: file
    toggle_hint:
      source: input_type
      value: file

# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
snippets:
  - name: ping_test
    file: ping_test.py
    input_type: cli

# ---------------------------------------------------------------------
# end of snippets section